module PoolParty
  module Resources
    
    class FileResource < Resource
      
      default_options(
        :content => "# File generated by PoolParty",
        :mode => "0644",
        :backup => 5,
        :owner => "root"
      )
      
      def self.has_method_name
        "file"
      end
            
      def print_to_chef        
        <<-EOE
template "<%= name %>" do
  content "<%= content %>"
  action :<%= exists? ? :create : :delete %>
  backup <%= backup %>
  mode <%= print_variable(mode) %>
  owner <%= print_variable(owner) %>
end
        EOE
      end
      
    end
    
  end
end