module PoolParty
  module Resources
    
    class FileResource < Resource
      
      default_options(
        :content  => "# File generated by PoolParty",
        :mode     => "0644",
        :backup   => 5,
        :owner    => "root"
      )
      
      def self.has_method_name
        "file"
      end
      
      def print_to_chef
        <<-EOE
template "<%= name %>" do
  source "<%= name %>.erb"
  action :<%= exists? ? :create : :delete %>
  backup <%= backup %>
  mode <%= print_variable(mode) %>
  owner <%= print_variable(owner) %>
end
        EOE
      end
      
      def template(*arg)
        if arg.empty?
          @template
        else
          file = arg.first
          @template = if File.file?(b = File.expand_path(file))
            b
          else
            raise PoolParty::PoolPartyError.create("TemplateNotFound", "The template #{file} could not be found when creating the file #{name}. Please check that it exists")
          end
        end
      end
      
      # A convenience helper to point to the path of the file
      def path
        name
      end
      
    end
    
  end
end