#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module CloudThrift
    class CloudQuery
      include ::Thrift::Struct
      NAME = 1

      ::Thrift::Struct.field_accessor self, :name
      FIELDS = {
        NAME => {:type => ::Thrift::Types::STRING, :name => 'name'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class CloudResponse
      include ::Thrift::Struct
      NAME = 1
      COMMAND = 2
      RESPONSE = 3

      ::Thrift::Struct.field_accessor self, :name, :command, :response
      FIELDS = {
        NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
        COMMAND => {:type => ::Thrift::Types::STRING, :name => 'command'},
        RESPONSE => {:type => ::Thrift::Types::LIST, :name => 'response', :element => {:type => ::Thrift::Types::STRING}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

  end
