#!/usr/bin/env bash

. /etc/profile
if [ $(/usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master)]; then
  echo "Run successfully" && exit 0
  else
  echo "Clearing old certs"
  HN=`hostname`
  if [[ $HN == "master" ]]; then
      /etc/init.d/puppetmaster stop;rm -rf /etc/poolparty/ssl;/etc/init.d/puppetmaster start
      /usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master
    else
      rm -rf /etc/poolparty/ssl/*;/usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master
  fi
fi