#!/usr/bin/env bash

# /var/lib/puppet/state/puppetdlock
. /etc/profile
HN=`hostname`
ps aux | grep puppetmaster | awk '{print $2}' | xargs kill
/etc/init.d/puppetmaster stop;rm /etc/poolparty/ssl/ca/signed/$HN.*;/etc/init.d/puppetmaster start;puppetmasterd --verbose