#!/usr/bin/env bash

. /etc/profile
# rm -rf /etc/puppet/ssl
if [ `hostname` -eq "master"];
  then
  /bin/sh puppetrerun
  else
  if [ `/usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master` ];
    then
    echo '';
    else
    /usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master
  fi
fi