#!/usr/bin/env bash

. /etc/profile
# rm -rf /etc/puppet/ssl
if [ `/usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master` ];
  then
  echo '';
  else
  ps aux | grep puppetmaster | awk '{print $2}' | xargs kill
  /etc/init.d/puppetmaster stop
  rm -rf /etc/puppet/ssl
  /etc/init.d/puppetmaster start
  /usr/sbin/puppetmasterd --verbose
  /usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master
fi