#!/usr/bin/env bash

. /etc/profile
# rm -rf /etc/puppet/ssl
if [ `/usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master` ];
  then
  echo '';
  else
  rm -rf /etc/puppet/ssl
  /usr/sbin/puppetd --onetime --no-daemonize --logdest syslog --server master
fi