%%
%% Autogenerated by Thrift
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(poolparty_types).

-include("poolparty_types.hrl").

-export([struct_info/1]).
%% struct cloudQuery

% -record(cloudQuery, {name}).

struct_info('cloudQuery') ->
  {struct, [{1, string}]}
;

%% struct cloudResponse

% -record(cloudResponse, {name, command, response}).

struct_info('cloudResponse') ->
  {struct, [{1, string},
  {2, string},
  {3, {list, string}}]}
;

struct_info('i am a dummy struct') -> undefined.
